controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

accueil:
  path: /accueil
  controller: App\Controller\HomeController::bonjour

redirecttoroute:
  path: /redirecttoroute
  controller: App\Controller\HomeController::aurevoir

redirecttolinkedin:
  path: /redirecttolinkedin
  controller: App\Controller\HomeController::redirecToLinkedIn


